name: Remote docker image scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  clair-scan-debian:
    name: Clair Scan for Debian
  
    env:
      DOCKER_TAG: vulnerables/web-dvwa
      CLAIR_REPORT: debian-remote-clair-report

    runs-on: ubuntu-latest

    steps:
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USR}} -p ${{secrets.DOCKER_TKN}}
      
    - name: Execute Clair scan
      uses: santander-group/clair-scan-action@main
      with:
        local: "no"
        updater: debian
        report_path: ${{env.CLAIR_REPORT}}.json
        report_format: 'json'
        image: ${{env.DOCKER_TAG}}

    - name: Store the report
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.CLAIR_REPORT}}
        path: ${{env.CLAIR_REPORT}}.json
        
    - name: Publish Scan Report
      uses: benauca/publish-clair-report@10b0daa67fca82001af3c637adde6d2557356d7f
      with:
        report_paths: ${{env.CLAIR_REPORT}}.json
        severity_level: 'Unknown'
        check_name: '${{env.CLAIR_REPORT}}'
        
  clair-scan-alpine:
    name: Clair Scan for Alpine
  
    env:
      DOCKER_TAG: vulnerables/web-dvwa
      CLAIR_REPORT: alpine-remote-clair-report

    runs-on: ubuntu-latest

    steps:
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USR}} -p ${{secrets.DOCKER_TKN}}
      
    - name: Execute Clair scan
      uses: santander-group/clair-scan-action@main
      with:
        local: "no"
        updater: alpine
        report_path: ${{env.CLAIR_REPORT}}.json
        report_format: 'json'
        image: ${{env.DOCKER_TAG}}

    - name: Store the report
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.CLAIR_REPORT}}
        path: ${{env.CLAIR_REPORT}}.json
        
    - name: Publish Scan Report
      uses: benauca/publish-clair-report@10b0daa67fca82001af3c637adde6d2557356d7f
      with:
        report_paths: ${{env.CLAIR_REPORT}}.json
        severity_level: 'Unknown'
        check_name: '${{env.CLAIR_REPORT}}'

  clair-scan-ubuntu:
    name: Clair Scan for Ubuntu
  
    env:
      DOCKER_TAG: vulnerables/web-dvwa
      CLAIR_REPORT: ubuntu-remote-clair-report

    runs-on: ubuntu-latest

    steps:
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USR}} -p ${{secrets.DOCKER_TKN}}
      
    - name: Execute Clair scan
      uses: santander-group/clair-scan-action@main
      with:
        local: "no"
        updater: ubuntu
        report_path: ${{env.CLAIR_REPORT}}.json
        report_format: 'json'
        image: ${{env.DOCKER_TAG}}

    - name: Store the report
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.CLAIR_REPORT}}
        path: ${{env.CLAIR_REPORT}}.json
        
    - name: Publish Scan Report
      uses: benauca/publish-clair-report@10b0daa67fca82001af3c637adde6d2557356d7f
      with:
        report_paths: ${{env.CLAIR_REPORT}}.json
        severity_level: 'Unknown'
        check_name: '${{env.CLAIR_REPORT}}'